blank_issues_enabled: false
contact_links:
  - name: LocoNet Discussions
    url: https://github.com/juhu1705/locodrive/discussions
    about: Please ask and answer questions about the LocoNet protocol here.
  - name: LocoNet Rocrail documentation
    url: https://wiki.rocrail.net/doku.php?id=loconet:ln-pe-en
    about: A listing on all LocoNet messages
  - name: locodrive documentation
    url: https://juhu1705.github.io/locodrive/doc/locodrive
    about: The rust doc of this project
  - name: locodrive wiki
    url: https://github.com/juhu1705/locodrive/wiki
    about: Work in progress wiki on the LocoNet and this locodrive
  - name: Model Train contribution project board
    url: https://github.com/users/juhu1705/projects/5
    about: A listing of all model railroad based Issues and their work state